# Enable this if you want to use per-world chat formats / per-world nametags for players
# - true / false
enable-multiworld-chat: false

# Please check if you have all PurePerms groups in your server here

# &0: Black, &1: Dark Blue, &2: Dark Green, &3: Dark Aqua, &4: Dark Red, &5: Dark Purple, &6: Gold, &7: Gray, &8: Dark Gray, &9: Blue
# &a: Green, &b: Aqua, &c: Red, &d: Light Purple, &e: Yellow, &f: White
# &k: Obfuscated, &l: Bold, &m: Strikethrough, &n: Underline, &o: Italic, &r: Reset

# Available chat tags: {display_name}, {msg}, {prefix}, {suffix}, {world}
groups:
  Guest:
    chat: "&3&l{prefix}&e[Guest]&f&r {display_name} &7> {msg}"
    nametag: "&3&l{prefix}&e[Guest]&f&r {display_name}"
    worlds: []
  Builder:
    chat: "&3&l{prefix}&b[Builder]&f&r {display_name} &7> {msg}"
    nametag: "&3&l{prefix}&b[Builder]&f&r {display_name}"
    worlds: []
  Moderator:
    chat: "&3&l{prefix}&3[Mod]&f&r {display_name} &7> {msg}"
    nametag: "&3&l{prefix}&3[Mod]&f&r {display_name}"
    worlds: []
  Admin:
    chat: "&3&l{prefix}&c[Admin]&f&r {display_name} &7> {msg}"
    nametag: "&3&l{prefix}&c[Admin]&f&r {display_name}"
    worlds: []
  CoOwner:
    chat: "&3&l{prefix}&4[CoOwner]&f&r {display_name} &7> {msg}"
    nametag: "&3&l{prefix}&4[CoOwner]&f&r {display_name}"
    worlds: []
  Owner:
    chat: "&3&l{prefix}&a[Owner]&f&r {display_name} &7> {msg}"
    nametag: "&3&l{prefix}&a[Owner]&f&r {display_name}"
    worlds: []